version: '3.3'

volumes:
  ps-coding-interview:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ps-coding-interview:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parkside
      MYSQL_USER: parkside
      MYSQL_PASSWORD: parkside
    ports:
      - 3306:3306
    networks:
      - global
  pma:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - mysql:mysql
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
    networks:
      - global
networks:
  global:
